sudo: required
services:
    - docker

before_install:
    - docker build -t mangzee/react-project -f Dockerfile_dev .

script:
    - docker run -e CI=true mangzee/react-project npm run test

deploy:
    provider: elasticbeanstalk
    region: ap-south-1 # Specify your region
    app: "react-project-docker" # Copy it from Elastic Beanstalk dashboard
    env: "ReactProjectDocker-env" # Copy it from Elastic Beanstalk dashboard
    bucket_name: "elasticbeanstalk-ap-south-1-611234080868"
    #bucket_path: "docker"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master
